services:
    wallet:
        build: .
        ports:
            - 8080:8080
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
            SPRING_DATASOURCE_USERNAME: ${DB_USER}
            SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
            SPRING_PROFILES_ACTIVE: prod
        restart: unless-stopped
        depends_on:
           db:
            condition: service_healthy
        volumes:
            - db-data:/var/lib/postgresql/data

    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d bank"]
            interval: 5s
            timeout: 5s
            retries: 2

volumes:
    db-data: